/// <reference preserve="true" path="./typings.ts" />

export type { ConditionalImport, ImportedModule } from './app/app.base.js';
export { AppFactory } from './app/app.factory.js';
export { CurrentUser } from './decorators/current-user.decorator.js';
export { ValidationSchema } from './decorators/validation-schema.decorator.js';
export type { AppVersion, DocsConfig } from './docs/docs.factory.js';
export { acceptLanguage } from './middleware/accept-language.middleware.js';
export { ConfigModule } from './modules/config/config.module.js';
export { ConfigService } from './modules/config/config.service.js';
export type { CryptoOptions } from './modules/crypto/crypto.config.js';
export { CryptoModule } from './modules/crypto/crypto.module.js';
export { CryptoService } from './modules/crypto/crypto.service.js';
export type { LoggingOptions } from './modules/logging/logging.config.js';
export { LoggingModule } from './modules/logging/logging.module.js';
export { LoggingService } from './modules/logging/logging.service.js';
export type { MailModuleOptions } from './modules/mail/mail.config.js';
export { MailModule } from './modules/mail/mail.module.js';
export { MailService } from './modules/mail/mail.service.js';
export type { PrismaModuleOptions } from './modules/prisma/prisma.config.js';
export { PRISMA_CLIENT_TOKEN } from './modules/prisma/prisma.config.js';
export { InjectModel, InjectPrismaClient } from './modules/prisma/prisma.decorators.js';
export { LibnestPrismaExtension } from './modules/prisma/prisma.extensions.js';
export { PrismaModule } from './modules/prisma/prisma.module.js';
export type { Model, PrismaModelKey, PrismaModelName } from './modules/prisma/prisma.types.js';
export { getModelToken } from './modules/prisma/prisma.utils.js';
export type { VirtualizationModuleOptions } from './modules/virtualization/virtualization.config.js';
export { VirtualizationModule } from './modules/virtualization/virtualization.module.js';
export { VirtualizationService } from './modules/virtualization/virtualization.service.js';
export { ParseSchemaPipe } from './pipes/parse-schema.pipe.js';
export { ValidObjectIdPipe } from './pipes/valid-object-id.pipe.js';
export { ValidationPipe } from './pipes/validation.pipe.js';
export { $BaseEnv } from './schemas/env.schema.js';
export type { BaseEnv } from './schemas/env.schema.js';
export { $MongoEnv } from './schemas/mongo-env.schema.js';
export type { RequestUser } from './user-config.js';
export type { BaseEnvSchema } from './utils/env.utils.js';
